name: arm-none-eabi-gcc

on:
  schedule:
    - cron: "0 0 1 * *" # at 00:00 on day-of-month 1
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update the GCC version to the latest
        run: |
          echo "Updating the GCC version to the latest"
          curl -o src/gcc.ts https://raw.githubusercontent.com/carlosperate/arm-none-eabi-gcc-action/main/src/gcc.ts
          curl -o src/gcc-versions.ts https://raw.githubusercontent.com/carlosperate/arm-none-eabi-gcc-action/refs/heads/main/src/gcc-versions.ts
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add src/gcc.ts
          git add src/gcc-versions.ts
          git diff --cached --quiet || git commit -m "Update GCC version to the latest"
          git push origin main

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        run: |
          echo "Installing dependencies"
          npm install
          echo "Building and pushing"
          npm run build && npm run node
          echo "Done"
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}

      - name: update description
        if: success()
        uses: peter-evans/dockerhub-description@v2
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ env.USERNAME }}/arm-none-eabi-gcc
